### PR TITLE
Fixing issues for env variables

### LINKED ISSUE #16: The Environment Variable sent in the initializer are not added to the process.
# The Environment Variable Issue

## Context

Trying to add an API Key for a mcp server like for brave search 

```
{
  "mcpServers": {
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "YOUR_API_KEY_HERE"
      }
    }
  }
}
```

## The Error
When initializing your MCPClient, the environment variable `BRAVE_API_KEY` wasn't being respected, causing this error:
```
Error: BRAVE_API_KEY environment variable is required.
```

## Why It Happened
Looking at the original `loadZshEnvironment` implementation:

```swift
private static func loadZshEnvironment() throws -> [String: String] {
    let process = Process()
    process.launchPath = "/bin/zsh"
    process.arguments = ["-c", "source ~/.zshenv; source ~/.zprofile; source ~/.zshrc; source ~/.zshrc; printenv"]
    let env = try getProcessStdout(process: process)

    if let path = env?.split(separator: "\n").filter({ $0.starts(with: "PATH=") }).last {
        return ["PATH": String(path.dropFirst("PATH=".count))]
    } else {
        return ProcessInfo.processInfo.environment
    }
}
```

This function had two critical flaws:

1. It returned ONLY the PATH variable from the shell environment (`return ["PATH": String(path)]`), discarding all other environment variables
2. It didn't accept or merge user-provided variables like `BRAVE_API_KEY`

## The potential Solution

```swift
private static func loadZshEnvironment(userEnv: [String: String]? = nil) throws -> [String: String] {
    // Load full shell environment
    let shellProcess = Process()
    shellProcess.executableURL = URL(fileURLWithPath: "/bin/zsh")
    shellProcess.arguments = ["-ilc", "printenv"]  // Interactive login shell
    
    let outputPipe = Pipe()
    shellProcess.standardOutput = outputPipe
    try shellProcess.run()
    shellProcess.waitUntilExit()
    
    // Parse ALL environment variables (not just PATH)
    var mergedEnv: [String: String] = [:]
    if let outputString = String(data: outputPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) {
        outputString.split(separator: "\n").forEach { line in
            let components = line.split(separator: "=", maxSplits: 1)
            if components.count == 2 {
                mergedEnv[String(components[0])] = String(components[1])
            }
        }
    }
    
    // Give priority to user-provided variables
    userEnv?.forEach { key, value in
        mergedEnv[key] = value
    }
    
    return mergedEnv
}
```

This works because:

1. We use `-ilc` flags to load a complete interactive login shell environment
2. We capture ALL environment variables, not just PATH
3. We accept `userEnv` as a parameter and overlay these values with priority
4. We preserve the original PATH from the shell, ensuring commands like `npx` are found

When you initialize your client with `env: ["BRAVE_API_KEY": "..."]`, this value will be properly included in the final environment.

# Complete Changes suggested by Claude:

```swift
private static func loadZshEnvironment(userEnv: [String: String]? = nil) throws -> [String: String] {
    // Load shell environment as base
    let shellProcess = Process()
    shellProcess.executableURL = URL(fileURLWithPath: "/bin/zsh")
    shellProcess.arguments = ["-ilc", "printenv"]
    
    let outputPipe = Pipe()
    shellProcess.standardOutput = outputPipe
    shellProcess.standardError = Pipe()
    
    try shellProcess.run()
    shellProcess.waitUntilExit()
    
    let data = outputPipe.fileHandleForReading.readDataToEndOfFile()
    guard let outputString = String(data: data, encoding: .utf8) else {
        logger.error("Failed to read environment from shell.")
        return ProcessInfo.processInfo.environment
    }
    
    // Parse shell environment
    var mergedEnv: [String: String] = [:]
    outputString.split(separator: "\n").forEach { line in
        let components = line.split(separator: "=", maxSplits: 1)
        guard components.count == 2 else { return }
        let key = String(components[0])
        let value = String(components[1])
        mergedEnv[key] = value
    }
    
    // Overlay user-defined environment variables explicitly
    userEnv?.forEach { key, value in
        mergedEnv[key] = value
    }
    
    // Log for debugging clarity
    logger.debug("Final merged environment: \(mergedEnv)")
    
    return mergedEnv
}
```

And

```swift
public static func stdioProcess(
  _ executable: String,
  args: [String] = [],
  cwd: String? = nil,
  env: [String: String]? = nil,
  verbose: Bool = false)
  throws -> Transport
{
  if verbose {
    let command = "\(executable) \(args.joined(separator: " "))"
    logger.log("Running ↪ \(command)")
  }

  // Create the process
  func path(for executable: String, env: [String: String]?) -> String? {
    guard !executable.contains("/") else {
      return executable
    }
    do {
      let path = try locate(executable: executable, env: env)
      return path.isEmpty ? nil : path
    } catch {
      // Most likely an error because we could not locate the executable
      return nil
    }
  }

  let process = Process()
  // In MacOS, zsh is the default since macOS Catalina 10.15.7. We can safely assume it is available.
  process.launchPath = "/bin/zsh"
  
  // Load shell environment and merge with user-provided environment
  process.environment = try loadZshEnvironment(userEnv: env)
  
  let command = "\(executable) \(args.joined(separator: " "))"
  process.arguments = ["-c"] + [command]

  // Working directory
  if let cwd {
    process.currentDirectoryPath = cwd
  }

  // Input/output
  let stdin = Pipe()
  let stdout = Pipe()
  let stderr = Pipe()
  process.standardInput = stdin
  process.standardOutput = stdout
  process.standardError = stderr

  return try stdioProcess(unlaunchedProcess: process, verbose: verbose)
}
```

### PR DESCRIPTION
**Pull request by jamesrochabrun**
## Summary

Aims to resolve https://github.com/gsabran/mcp-swift-sdk/issues/16

Tested this with current ClientChatDemo project Using Brave search 

## Details

### CODE REVIEW

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 1]
```diff
@@ -46,64 +45,59 @@ extension JSONRPCSetupError: LocalizedError {
...
-
-    let process = Process()
-    // In MacOS, zsh is the default since macOS Catalina 10.15.7. We can safely assume it is available.
-    process.launchPath = "/bin/zsh"
-    if let executable = path(for: executable, env: env) {
+      
+      let process = Process()
+      // In MacOS, zsh is the default since macOS Catalina 10.15.7. We can safely assume it is available.
+      process.launchPath = "/bin/zsh"
+
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: can we keep the initial condition? If the executable is found no need to load the env

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 2]
```diff
@@ -46,64 +45,59 @@ extension JSONRPCSetupError: LocalizedError {
 extension Transport {
 
   // MARK: Public
-
-  /// Creates a new `Transport` by launching the given executable with the specified arguments and attaching to its standard IO.
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: keep?

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 3]
```diff
@@ -211,22 +205,46 @@ extension Transport {
...
-      return ["PATH": String(path.dropFirst("PATH=".count))]
-    } else {
-      return ProcessInfo.processInfo.environment
-    }
-  }
-
+   
+   private static func loadZshEnvironment(userEnv: [String: String]? = nil) throws -> [String: String] {
+      // Load shell environment as base
+      let shellProcess = Process()
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: If we add `userEnv` to the process here, does it get merged automatically when calling `printenv` ?

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 4]
```diff
@@ -211,22 +205,46 @@ extension Transport {
...
+      shellProcess.executableURL = URL(fileURLWithPath: "/bin/zsh")
+      shellProcess.arguments = ["-ilc", "printenv"]
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: nice!

**Review by gsabran — COMMENTED** [review]
Looking good, some comments

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift (hunk 1 above)
Comment (jamesrochabrun) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: done!

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift (hunk 3 above)
Comment (jamesrochabrun) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: I don't think so? environment variables assigned to a process don't automatically merge with the shell's environment when running commands. I updated the code to do so, what do you think?

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 5]
```diff
@@ -212,19 +213,51 @@ extension Transport {
...
+    shellProcess.executableURL = URL(fileURLWithPath: "/bin/zsh")
 
-    if let path = env?.split(separator: "\n").filter({ $0.starts(with: "PATH=") }).last {
-      return ["PATH": String(path.dropFirst("PATH=".count))]
+    // When userEnv exists, we need to explicitly export these variables in the shell
+    // before running printenv so they're included in the environment output
+    if let userEnv = userEnv, !userEnv.isEmpty {
+      var exportCommands = userEnv.map { key, value in
+        "export \(key)=\(value.replacingOccurrences(of: "\"", with: "\\\""))"
+      }.joined(separator: "; ")
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: wouldn't `shellProcess.environment = userEnv` do the same?

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 6]
```diff
@@ -212,19 +213,51 @@ extension Transport {
...
+      guard components.count == 2 else { return }
+      let key = String(components[0])
+      let value = String(components[1])
+      mergedEnv[key] = value
+    }
+
+    // Debug logging to verify environment was properly merged
+    logger.debug("Shell environment loaded with user variables successfully merged")
+
+    return mergedEnv
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: nit:
```suggestion
    // Debug logging to verify environment was properly merged
    logger.debug("Shell environment loaded with user variables successfully merged")

    return outputString
      .split(separator: "\n")
      .reduce(into: [String: String]()) { result, line in
          // Parse the env variable key / value
          let components = line.split(separator: "=", maxSplits: 1)
          guard components.count == 2 else { return }
          result[String(components[0])] = String(components[1])
      }
```

**Review by gsabran — COMMENTED** [review]
Looking good! Two nit comments. Can you rebase before merging? I simplified the linting and as there's no pre-merge checks not rebasing would lead to issues on main.

(`swiftformat --config rules.swiftformat .`)

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift (hunk 5 above)
Comment (jamesrochabrun) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: Disclaimer: with assistance of Claude

My understanding is that setting shellProcess.environment = userEnv wouldn't have the same effect because:

We're using zsh with -il flags which loads configuration files that might override environment variables
The explicit export commands ensure the variables are definitely set within the shell session where printenv runs
This approach guarantees the user variables appear in the printenv output, regardless of how zsh loads its environment.

Comment (gsabran) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: You can't trust those AI
Screenshot 2025-03-10 at 11 07 44 AM

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift [hunk 7]
```diff
@@ -208,19 +209,48 @@ extension Transport {
...
+        "export \(key)=\(value.replacingOccurrences(of: "\"", with: "\\\""))"
+      }.joined(separator: "; ")
 
-    if let path = env?.split(separator: "\n").filter({ $0.starts(with: "PATH=") }).last {
-      return ["PATH": String(path.dropFirst("PATH=".count))]
+      exportCommands += "; printenv"
+      shellProcess.arguments = ["-ilc", exportCommands]
     } else {
+      shellProcess.arguments = ["-ilc", "printenv"]
+    }
```
Comment (gsabran) [inline MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]:
```swift
shellProcess.environment = userEnv.isEmpty ? ProcessInfo.processInfo.environment : userEnv
shellProcess.arguments = ["-ilc", "printenv"]
```

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift (hunk 5 above)
Comment (jamesrochabrun) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: @gsabran I am not sure why I am not able to see the suggestion you shared yesterday, do you mind adding it as comment so I can update the code? thanks!

File: MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift (hunk 7 above)
Comment (jamesrochabrun) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]: updated!

Comment (jamesrochabrun) [reply MCPClient/Sources/stdioTransport/DataChannel+StdioProcess.swift]:
```swift
  private static func loadZshEnvironment(userEnv: [String: String]? = nil) throws -> [String: String] {
    // Load shell environment as base
    let shellProcess = Process()
    shellProcess.executableURL = URL(fileURLWithPath: "/bin/zsh")

    // Set process environment - either use userEnv if it exists and isn't empty, or use system environment
    if let env = userEnv, !env.isEmpty {
      shellProcess.environment = env
    } else {
      shellProcess.environment = ProcessInfo.processInfo.environment
    }

    shellProcess.arguments = ["-ilc", "printenv"]

    let outputPipe = Pipe()
    shellProcess.standardOutput = outputPipe
    shellProcess.standardError = Pipe()

    try shellProcess.run()
    shellProcess.waitUntilExit()

    let data = outputPipe.fileHandleForReading.readDataToEndOfFile()
    guard let outputString = String(data: data, encoding: .utf8) else {
      logger.error("Failed to read environment from shell.")
      return ProcessInfo.processInfo.environment
    }

    // Parse shell environment
    return outputString
      .split(separator: "\n")
      .reduce(into: [String: String]()) { result, line in
        let components = line.split(separator: "=", maxSplits: 1)
        guard components.count == 2 else { return }
        result[String(components[0])] = String(components[1])
      }
  }
```

**Review by gsabran — APPROVED** [review]
Thanks a lot!
